import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  pinkCircle: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 150,
    top: -10,
    left: -100,
    opacity: 0.3,
    zIndex: 0,
    shadowColor: '#FFA500',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 5,
  },
  pinkCircleRight: {
    position: 'absolute',
    width: 250,
    height: 250,
    borderRadius: 150,
    top: 50,
    right: -100,
    opacity: 0.3,
    zIndex: 0,
    shadowColor: '#FFA500',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 5,
  },
  orangeCircleBottom: {
    position: 'absolute',
    width: 200,
    height: 200,
    borderRadius: 100,
    bottom: '10%',
    left: -80,
    opacity: 0.3,
    zIndex: 0,
    shadowColor: '#FF8C00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 25,
    elevation: 5,
  },
  pinkCircleBottomRight: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    bottom: '25%',
    right: -70,
    opacity: 0.3,
    zIndex: 0,
    shadowColor: '#FFA500',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 5,
  },
  scrollContent: {
    flexGrow: 1,
    padding: '5%',
    paddingBottom: 120,
    paddingTop: '25%',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  welcomeText: {
    fontSize: 24,
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  subHeaderText: {
    fontSize: 14,
    color: '#666',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#eee',
    marginTop: '15%',
    marginBottom: '15%',
    paddingHorizontal: 16,
    height: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#222',
  },
  searchIcon: {
    marginLeft: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#222',
  },
  tilesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  cardList: {
    marginBottom: 25,
    paddingHorizontal: 5,
  },
  mostBookedSection: {
    marginTop: 20,
  },
  mostBookedList: {
    marginBottom: 20,
  },
  mostBookedCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
  },
  mostBookedImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginRight: 15,
  },
  mostBookedContent: {
    flex: 1,
  },
  mostBookedTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 4,
  },
  mostBookedDescription: {
    fontSize: 12,
    color: '#666',
    marginBottom: 8,
    lineHeight: 16,
  },
  viewButton: {
    backgroundColor: '#EDAE49',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  viewButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  // Search Results Styles
  searchResultsContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  searchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  searchHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222',
    flex: 1,
  },
  clearSearchText: {
    fontSize: 14,
    color: '#EDAE49',
    fontWeight: '500',
  },
  searchResultsList: {
    // Remove maxHeight to allow proper scrolling in main ScrollView
  },
  searchResultItem: {
    flexDirection: 'row',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f5f5f5',
  },
  searchResultImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  searchResultContent: {
    flex: 1,
  },
  searchResultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 2,
  },
  searchResultCategory: {
    fontSize: 12,
    color: '#EDAE49',
    marginBottom: 4,
    fontWeight: '500',
  },
  searchResultRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#222',
    marginLeft: 4,
  },
  reviewText: {
    fontSize: 11,
    color: '#666',
    marginLeft: 4,
  },
  searchResultDescription: {
    fontSize: 12,
    color: '#666',
    lineHeight: 16,
    marginBottom: 4,
  },
  searchResultPrice: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#EDAE49',
    marginTop: 4,
  },

  // Quick Search Suggestions
  quickSearchContainer: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  quickSearchTitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  quickSearchTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickSearchTag: {
    backgroundColor: '#F5F5F5',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  quickSearchTagText: {
    fontSize: 12,
    color: '#666',
    fontWeight: '500',
  },

  // Empty Search State Styles
  emptySearchContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptySearchTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 16,
    marginBottom: 8,
  },
  emptySearchText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  browseAllButton: {
    backgroundColor: '#EDAE49',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  browseAllButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
});

export default homeStyles;
